<nav class="cs-product-navigation" data-mage-init='{ "MageSuite_ProductNavigation/js/product-navigation": {} }'>
    <ul class="cs-product-navigation__list">
        <a href="#" class="cs-product-navigation__link cs-product-navigation__link--back"><?= __('Back to category'); ?></a>
        <a href="#" class="cs-product-navigation__link cs-product-navigation__link--prev"><?= __('Previous product'); ?></a>
        <a href="#" class="cs-product-navigation__link cs-product-navigation__link--next"><?= __('Next product'); ?></a>
    </ul>
</nav>